export default {
  REPLACE_LIST: 'CANDIDATE_LIST/REPLACE_LIST',
  ADD_CANDIDATE: 'CANDIDATE_LIST/ADD',
  REMOVE_CANDIDATE: 'CANDIDATE_LIST/REMOVE',
  UPDATE_CANDIDATE: 'CANDIDATE_LIST/UPDATE',
  CHANGE_SORT_BY: 'CANDIDATE_LIST/CHANGE_SORT_BY',
  CHANGE_SORT_DIRECTION: 'CANDIDATE_LIST/CHANGE_SORT_DIRECTION',
};
